// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranTuanAnh_BaiTap.Models;

#nullable disable

namespace TranTuanAnh_BaiTap.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250621013137_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TranTuanAnh_BaiTap.Models.TuanAnh_ChiTietDonHang", b =>
                {
                    b.Property<int>("ChiTietDonHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietDonHangID"));

                    b.Property<int>("DonHangID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("XeID")
                        .HasColumnType("int");

                    b.HasKey("ChiTietDonHangID");

                    b.HasIndex("DonHangID");

                    b.HasIndex("XeID");

                    b.ToTable("TuanAnh_ChiTietDonHang");
                });

            modelBuilder.Entity("TranTuanAnh_BaiTap.Models.TuanAnh_DonHang", b =>
                {
                    b.Property<int>("DonHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonHangID"));

                    b.Property<string>("KhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.HasKey("DonHangID");

                    b.ToTable("TuanAnh_DonHang");
                });

            modelBuilder.Entity("TranTuanAnh_BaiTap.Models.TuanAnh_HangXe", b =>
                {
                    b.Property<int>("HangXeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HangXeID"));

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HangXeID");

                    b.ToTable("TuanAnh_HangXe");
                });

            modelBuilder.Entity("TranTuanAnh_BaiTap.Models.TuanAnh_Xe", b =>
                {
                    b.Property<int>("XeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("XeID"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HangXeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("XeID");

                    b.HasIndex("HangXeID");

                    b.ToTable("TuanAnh_Xe");
                });

            modelBuilder.Entity("TranTuanAnh_BaiTap.Models.TuanAnh_ChiTietDonHang", b =>
                {
                    b.HasOne("TranTuanAnh_BaiTap.Models.TuanAnh_DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TranTuanAnh_BaiTap.Models.TuanAnh_Xe", "Xe")
                        .WithMany()
                        .HasForeignKey("XeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("TranTuanAnh_BaiTap.Models.TuanAnh_Xe", b =>
                {
                    b.HasOne("TranTuanAnh_BaiTap.Models.TuanAnh_HangXe", "HangXe")
                        .WithMany("DanhSachXe")
                        .HasForeignKey("HangXeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangXe");
                });

            modelBuilder.Entity("TranTuanAnh_BaiTap.Models.TuanAnh_DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("TranTuanAnh_BaiTap.Models.TuanAnh_HangXe", b =>
                {
                    b.Navigation("DanhSachXe");
                });
#pragma warning restore 612, 618
        }
    }
}
